### PR TITLE
chore: fixes short write error.

### PR DESCRIPTION
**Pull request by jcchavezs**
Related https://github.com/caddyserver/caddy/pull/5952#issuecomment-1827462757

### CODE REVIEW

**Comment by jcchavezs** [comment]
So we have to define what to do here. The test fails as:

https://github.com/corazawaf/coraza-caddy/actions/runs/7002992650/job/19047820525#step:6:89

`[Fail] could not do http request: Get "http://localhost:8080/response-headers?pass=leak": EOF`

This is because before we were returning a content-length but the actual response body was empty (due to interruption) but caddy was returning `nil` and hence no error https://github.com/caddyserver/caddy/pull/5952/files#diff-a248c9a1ec018edea8b377d155bc1df1a642bf79d00ababb5cdacc6b86c5733dL968.

**Comment by M4tteoP** [comment]
What is the client receiving now that caddy is returning an error? Should we make the e2e-tester more error-tolerant?

**Comment by jcchavezs** [comment]
I think we should not fail because this is a legit request, we should just deny it.

**Comment by jcchavezs** [comment]
PTAL @M4tteoP

**Review by M4tteoP — APPROVED** [review]
Looks good to me! And it is actually an approach that we already used https://github.com/corazawaf/coraza-caddy/pull/96#discussion_r1287289408.
The interceptor was originally copied from coraza upstream ( https://github.com/corazawaf/coraza/blob/main/http/interceptor.go), can this changes also be ported upstream? Also, vice-versa, we have https://github.com/corazawaf/coraza/pull/923, https://github.com/corazawaf/coraza/pull/925

**Comment by jcchavezs** [comment]
#923 I dont know but I am tempted to say yes #925 indeed, do you mind
porting it?

**Pull request merged**
